import { useEffect, useState } from 'react';
import { BarChart3, CheckCircle2, FileText, Mail, Search, Shield, Users, XCircle } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

type Tab='overview'|'users'|'providers'|'orders'|'emails'|'templates'|'audit'|'settings';
const roles=['tenant','provider','driver','merchant','admin'];
export default function AdminDashboard(){
 const {session,signOut}=useAuth(); const [tab,setTab]=useState<Tab>('overview'); const [data,setData]=useState<any>(null); const [q,setQ]=useState(''); const [role,setRole]=useState(''); const [busy,setBusy]=useState<string|null>(null); const [msg,setMsg]=useState('');
 const headers={Authorization:`Bearer ${session?.access_token}`,'Content-Type':'application/json'};
 const load=async()=>{if(!session)return;let path='/api/admin/overview';if(tab==='users')path=`/api/admin/users?q=${encodeURIComponent(q)}&role=${encodeURIComponent(role)}`;if(tab==='providers')path='/api/admin/providers';if(tab==='orders')path='/api/admin/orders';if(tab==='emails')path='/api/admin/emails';if(tab==='templates')path='/api/admin/email-templates';if(tab==='audit')path='/api/admin/audit';if(tab==='settings')path='/api/admin/settings';const r=await fetch(path,{headers});const j=await r.json().catch(()=>({}));setData(j.data??null)};
 useEffect(()=>{void load()},[tab,q,role,session?.access_token]);
 const action=async(url:string,method='POST',body?:any)=>{setBusy(url);setMsg('');const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));setBusy(null);if(!r.ok){setMsg(j.error||'Action failed');return}setMsg('Saved successfully');void load()};
 const nav:[Tab,string][]=[['overview','Overview'],['users','Users'],['providers','Providers'],['orders','Orders'],['emails','Emails'],['templates','Templates'],['audit','Audit'],['settings','Settings']];
 return <div className="platform-page"><div className="admin-shell"><header><div><small>OmniServe Control Plane</small><h1>Administration</h1><p className="muted">Govern users, marketplace operations, notifications, email and platform configuration.</p></div><button onClick={()=>signOut()}>Sign out</button></header><nav className="admin-tabs">{nav.map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>{msg&&<div className="success-banner" role="status">{msg}</div>}{tab==='users'&&<div className="admin-toolbar"><div className="search-wrap"><Search size={15}/><input placeholder="Search name or email" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</select></div>}{tab==='overview'&&data&&<div className="stat-grid">{Object.entries(data).map(([k,v])=><article key={k}><strong>{String(v)}</strong><span>{k.replaceAll('_',' ')}</span></article>)}</div>}{tab==='users'&&Array.isArray(data)&&<div className="data-table"><div className="table-head"><span>User</span><span>Role</span><span>Status</span><span>Actions</span></div>{data.map((u:any)=><div className="table-row" key={u.id}><div><strong>{u.name||'Unnamed'}</strong><small>{u.email}</small></div><select value={u.role} onChange={e=>void action(`/api/admin/users/${u.id}/role`,'PATCH',{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><span>{u.suspendedAt?<b className="status-bad">Suspended</b>:<b className="status-good">Active</b>}</span><button disabled={busy?.includes(u.id)} onClick={()=>void action(`/api/admin/users/${u.id}/${u.suspendedAt?'restore':'suspend'}`)}>{u.suspendedAt?<CheckCircle2 size={15}/>:<XCircle size={15}/>} {u.suspendedAt?'Restore':'Suspend'}</button></div>)}</div>}{['providers','orders','emails','templates','audit','settings'].includes(tab)&&Array.isArray(data)&&<div className="data-table"><div className="json-grid">{data.map((x:any,i:number)=><article key={x.id||x.key||i}><pre>{JSON.stringify(x,null,2)}</pre>{tab==='templates'&&<button onClick={()=>{const subject=window.prompt('Subject',x.subject);if(subject!==null)void action(`/api/admin/email-templates/${x.id}`,'PATCH',{subject})}}>Edit subject</button>}</article>)}</div></div>}{tab==='overview'&&<div className="admin-feature-grid"><article><Users/><h2>User governance</h2><p>Role changes and suspension are audited and protected by admin RBAC.</p></article><article><Mail/><h2>Email operations</h2><p>Inspect queued, failed and delivered transactional messages.</p></article><article><Shield/><h2>Security</h2><p>Audit events use hashed request IPs and never store passwords or service keys.</p></article><article><BarChart3/><h2>Operations</h2><p>Orders, providers, stores and drivers remain visible from one control plane.</p></article></div>}</div></div>
}
